from __future__ import annotations

import io
import json
import re
import zipfile
from datetime import datetime

from flask import Blueprint, jsonify, request, send_file

from reportlab.lib import colors
from reportlab.lib.enums import TA_RIGHT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.graphics.shapes import Drawing, Rect

from app.models import DiagnosisReport, UserActivity, db
from app.utils.decorators import diagnosis_access_required
from app.utils.jwt_utils import get_current_user_id


reports_bp = Blueprint('reports', __name__)

PDF_MIMETYPE = 'application/pdf'

# ---------------------------------------------------------------------------
# Brand palette
# ---------------------------------------------------------------------------
BRAND_PRIMARY = colors.HexColor('#0f4c5c')   # deep teal (header band)
BRAND_ACCENT = colors.HexColor('#0ea5b8')    # bright teal (bars / highlights)
COLOR_DANGER = colors.HexColor('#dc2626')    # verdict: condition detected
COLOR_SAFE = colors.HexColor('#16a34a')      # verdict: no condition detected
COLOR_NEUTRAL = colors.HexColor('#64748b')   # verdict: inconclusive / unknown
BG_LIGHT = colors.HexColor('#f1f5f9')
TEXT_DARK = colors.HexColor('#1e293b')
TEXT_MUTED = colors.HexColor('#64748b')
BORDER = colors.HexColor('#e2e8f0')

HEADER_HEIGHT = 70
FOOTER_DISCLAIMER = (
    "This report is generated by an AI-assisted system and is intended to support, not replace, "
    "professional clinical judgment. Please consult a qualified healthcare provider."
)


def _safe_filename(value: str) -> str:
    value = re.sub(r'[^A-Za-z0-9._-]+', '_', value or 'report')
    return value.strip('_') or 'report'


def _extract_payload(data: dict) -> dict:
    payload = data.get('results')
    if isinstance(payload, dict):
        return payload
    payload = data.get('report')
    if isinstance(payload, dict):
        return payload
    return data if isinstance(data, dict) else {}


def _build_metadata(payload: dict, data: dict) -> dict:
    report_type = (data.get('report_type') or payload.get('mode') or 'single').strip().lower()
    source_files = data.get('source_files')
    if not isinstance(source_files, list):
        source_file = data.get('source_file')
        source_files = [source_file] if source_file else []
    source_files = [str(item) for item in source_files if str(item).strip()]

    if report_type == 'batch':
        title = data.get('title') or f"Batch EEG Report - {datetime.utcnow().strftime('%Y-%m-%d %H:%M')}"
        summary = data.get('summary') or f"Batch diagnosis saved with {payload.get('n_test_samples', 0)} test samples"
        verdict = data.get('verdict') or f"Accuracy {payload.get('accuracy', 0):.2f}"
        confidence = data.get('confidence')
        if confidence is None:
            confidence = payload.get('accuracy')
    else:
        title = data.get('title') or f"Single EEG Report - {datetime.utcnow().strftime('%Y-%m-%d %H:%M')}"
        ensemble = payload.get('ensemble', {}) if isinstance(payload.get('ensemble'), dict) else {}
        task = payload.get('tasks', {}).get('task2', {}) if isinstance(payload.get('tasks'), dict) else {}
        verdict = data.get('verdict') or ensemble.get('verdict') or 'UNKNOWN'
        confidence = data.get('confidence')
        if confidence is None:
            confidence = ensemble.get('avg_dementia_prob') or task.get('confidence')
        summary = data.get('summary') or ensemble.get('interpretation') or 'Single patient EEG diagnosis report'

    return {
        'report_type': report_type,
        'title': title[:160],
        'source_files': source_files,
        'verdict': verdict[:120] if isinstance(verdict, str) else str(verdict),
        'confidence': confidence,
        'summary': summary[:255] if isinstance(summary, str) else str(summary),
    }


# ---------------------------------------------------------------------------
# PDF rendering helpers
# ---------------------------------------------------------------------------

def _format_confidence(value) -> str:
    try:
        num = float(value)
    except (TypeError, ValueError):
        return 'N/A'
    pct = num * 100 if 0 <= num <= 1 else num
    return f"{pct:.2f}%"


def _verdict_color(verdict: str):
    text = (verdict or '').upper()
    if any(k in text for k in ('NO ', 'NOT ', 'NEGATIVE', 'NORMAL', 'HEALTHY')):
        return COLOR_SAFE
    if 'DEMENTIA' in text or 'DETECTED' in text or 'POSITIVE' in text:
        return COLOR_DANGER
    return COLOR_NEUTRAL


def _format_label(key: str) -> str:
    return str(key).replace('_', ' ').strip().title()


def _format_value(value) -> str:
    if isinstance(value, bool):
        return 'Yes' if value else 'No'
    if isinstance(value, float):
        if 0 <= value <= 1:
            return f"{value * 100:.2f}%"
        return f"{value:.2f}"
    if value is None or value == '':
        return 'N/A'
    return str(value)


def _styles():
    base = getSampleStyleSheet()
    return {
        'MainTitle': ParagraphStyle(
            'MainTitle', parent=base['Title'], fontName='Helvetica-Bold',
            fontSize=16, textColor=TEXT_DARK, alignment=0, spaceAfter=4,
        ),
        'SectionHeading': ParagraphStyle(
            'SectionHeading', parent=base['Heading2'], fontName='Helvetica-Bold',
            fontSize=12.5, textColor=BRAND_PRIMARY, spaceBefore=14, spaceAfter=8,
        ),
        'SubHeading': ParagraphStyle(
            'SubHeading', parent=base['Heading3'], fontName='Helvetica-Bold',
            fontSize=10.5, textColor=TEXT_DARK, spaceBefore=6, spaceAfter=4,
        ),
        'Body': ParagraphStyle(
            'Body', parent=base['Normal'], fontName='Helvetica',
            fontSize=10, textColor=TEXT_DARK, leading=14,
        ),
        'BodyMuted': ParagraphStyle(
            'BodyMuted', parent=base['Normal'], fontName='Helvetica-Oblique',
            fontSize=9.5, textColor=TEXT_MUTED, leading=13,
        ),
        'CellLabel': ParagraphStyle(
            'CellLabel', parent=base['Normal'], fontName='Helvetica',
            fontSize=9.5, textColor=TEXT_MUTED,
        ),
        'CellValue': ParagraphStyle(
            'CellValue', parent=base['Normal'], fontName='Helvetica-Bold',
            fontSize=9.5, textColor=TEXT_DARK,
        ),
        'CellValueRight': ParagraphStyle(
            'CellValueRight', parent=base['Normal'], fontName='Helvetica-Bold',
            fontSize=9.5, textColor=TEXT_DARK, alignment=TA_RIGHT,
        ),
        'VerdictText': ParagraphStyle(
            'VerdictText', parent=base['Normal'], fontName='Helvetica-Bold',
            fontSize=15, textColor=colors.white,
        ),
        'VerdictConfidence': ParagraphStyle(
            'VerdictConfidence', parent=base['Normal'], fontName='Helvetica',
            fontSize=10, textColor=colors.white, alignment=TA_RIGHT,
        ),
    }


def _bar_drawing(fraction: float, width: float, height: float, color) -> Drawing:
    fraction = max(0.0, min(fraction, 1.0))
    d = Drawing(width, height)
    d.add(Rect(0, 0, width, height, fillColor=BG_LIGHT, strokeColor=None, rx=height / 2, ry=height / 2))
    fill_width = max(width * fraction, height) if fraction > 0 else 0
    if fill_width:
        d.add(Rect(0, 0, fill_width, height, fillColor=color, strokeColor=None, rx=height / 2, ry=height / 2))
    return d


def _scalar_kv_table(styles, data: dict, exclude=()):
    rows = []
    for key, value in data.items():
        if key in exclude or isinstance(value, (dict, list)):
            continue
        rows.append([
            Paragraph(_format_label(key), styles['CellLabel']),
            Paragraph(_format_value(value), styles['CellValue']),
        ])
    if not rows:
        return None
    table = Table(rows, colWidths=[160, 300])
    table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('LINEBELOW', (0, 0), (-1, -2), 0.5, BORDER),
    ]))
    return table


def _band_powers_section(styles, band_powers):
    if not isinstance(band_powers, dict) or not band_powers:
        return []
    numeric_items = []
    for key, value in band_powers.items():
        try:
            numeric_items.append((key, float(value)))
        except (TypeError, ValueError):
            continue
    if not numeric_items:
        return []

    max_val = max(v for _, v in numeric_items) or 1.0
    bar_width, bar_height = 210, 10
    rows = []
    for key, value in numeric_items:
        bar = _bar_drawing(value / max_val, bar_width, bar_height, BRAND_ACCENT)
        rows.append([
            Paragraph(_format_label(key), styles['CellLabel']),
            bar,
            Paragraph(f"{value * 100:.2f}%" if 0 <= value <= 1 else f"{value:.3f}", styles['CellValueRight']),
        ])

    table = Table(rows, colWidths=[90, bar_width + 12, 70])
    table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('LINEBELOW', (0, 0), (-1, -2), 0.5, BORDER),
    ]))
    return [Paragraph('Frequency Band Powers', styles['SectionHeading']), table, Spacer(1, 12)]


def _ensemble_section(styles, ensemble):
    if not isinstance(ensemble, dict) or not ensemble:
        return []
    flow = [Paragraph('Model Ensemble Analysis', styles['SectionHeading'])]
    interpretation = ensemble.get('interpretation')
    table = _scalar_kv_table(styles, ensemble, exclude=('interpretation', 'verdict'))
    if table:
        flow.append(table)
        flow.append(Spacer(1, 8))
    if interpretation:
        flow.append(Paragraph(str(interpretation), styles['BodyMuted']))
        flow.append(Spacer(1, 12))
    return flow


def _tasks_section(styles, tasks):
    if not isinstance(tasks, dict) or not tasks:
        return []
    flow = [Paragraph('Per-Task Breakdown', styles['SectionHeading'])]
    for task_name, task_data in tasks.items():
        if not isinstance(task_data, dict) or not task_data:
            continue
        flow.append(Paragraph(_format_label(task_name), styles['SubHeading']))
        table = _scalar_kv_table(styles, task_data)
        if table:
            flow.append(table)
        flow.append(Spacer(1, 8))
    return flow


def _additional_data_section(styles, payload: dict, consumed_keys):
    remaining = {
        k: v for k, v in payload.items()
        if k not in consumed_keys and not isinstance(v, (dict, list))
    }
    if not remaining:
        return []
    table = _scalar_kv_table(styles, remaining)
    if not table:
        return []
    return [Paragraph('Additional Details', styles['SectionHeading']), table, Spacer(1, 12)]


def _draw_header_footer(canv, doc, report):
    canv.saveState()
    width, height = letter

    canv.setFillColor(BRAND_PRIMARY)
    canv.rect(0, height - HEADER_HEIGHT, width, HEADER_HEIGHT, fill=1, stroke=0)
    canv.setFillColor(colors.white)
    canv.setFont('Helvetica-Bold', 16)
    canv.drawString(40, height - 32, 'NeuroCare AI')
    canv.setFont('Helvetica', 9.5)
    canv.drawString(40, height - 48, 'AI-Assisted EEG Diagnosis Report')

    generated = datetime.utcnow().strftime('%b %d, %Y  %H:%M UTC')
    canv.setFont('Helvetica', 8.5)
    canv.drawRightString(width - 40, height - 32, f"Report #{report.id}")
    canv.drawRightString(width - 40, height - 48, f"Generated {generated}")

    canv.setFillColor(TEXT_MUTED)
    canv.setFont('Helvetica', 7.5)
    canv.drawString(40, 28, FOOTER_DISCLAIMER)
    canv.drawRightString(width - 40, 28, f"Page {doc.page}")
    canv.restoreState()


def _render_report_pdf(report: DiagnosisReport) -> bytes:
    styles = _styles()
    payload = report.get_report_json() or {}
    source_files = report.get_source_files() or []

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=HEADER_HEIGHT + 25,
        bottomMargin=55,
        leftMargin=40,
        rightMargin=40,
        title=report.title or 'EEG Diagnosis Report',
        author='NeuroCare AI',
    )

    story = []

    story.append(Paragraph(report.title or 'EEG Diagnosis Report', styles['MainTitle']))
    created_at = report.created_at.strftime('%B %d, %Y at %H:%M') if report.created_at else 'N/A'
    report_type_label = _format_label(report.report_type or 'single')
    story.append(Paragraph(f"{report_type_label} Report  &bull;  Created {created_at}", styles['BodyMuted']))
    story.append(Spacer(1, 14))

    overview_rows = [
        [Paragraph('Report ID', styles['CellLabel']), Paragraph(str(report.id), styles['CellValue'])],
        [Paragraph('Type', styles['CellLabel']), Paragraph(report_type_label, styles['CellValue'])],
        [Paragraph('Source File(s)', styles['CellLabel']),
         Paragraph(', '.join(source_files) if source_files else 'N/A', styles['CellValue'])],
    ]
    overview_table = Table(overview_rows, colWidths=[110, 350])
    overview_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('BACKGROUND', (0, 0), (-1, -1), BG_LIGHT),
        ('BOX', (0, 0), (-1, -1), 0.5, BORDER),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
        ('LINEBELOW', (0, 0), (-1, -2), 0.5, BORDER),
    ]))
    story.append(overview_table)
    story.append(Spacer(1, 16))

    verdict_color = _verdict_color(report.verdict)
    confidence_text = _format_confidence(report.confidence)
    verdict_table = Table(
        [[Paragraph(report.verdict or 'UNKNOWN', styles['VerdictText']),
          Paragraph(f"Confidence<br/><b>{confidence_text}</b>", styles['VerdictConfidence'])]],
        colWidths=[320, 140],
    )
    verdict_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), verdict_color),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LEFTPADDING', (0, 0), (0, 0), 18),
        ('RIGHTPADDING', (1, 0), (1, 0), 18),
        ('TOPPADDING', (0, 0), (-1, -1), 14),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 14),
        ('ROUNDEDCORNERS', [8, 8, 8, 8]),
    ]))
    story.append(verdict_table)
    story.append(Spacer(1, 16))

    if report.summary:
        story.append(Paragraph('Summary', styles['SectionHeading']))
        story.append(Paragraph(report.summary, styles['Body']))
        story.append(Spacer(1, 6))

    story.append(HRFlowable(width='100%', thickness=0.6, color=BORDER, spaceBefore=6, spaceAfter=6))

    consumed_keys = {'mode', 'ensemble', 'band_powers', 'tasks'}
    story.extend(_band_powers_section(styles, payload.get('band_powers')))
    story.extend(_ensemble_section(styles, payload.get('ensemble')))
    story.extend(_tasks_section(styles, payload.get('tasks')))
    story.extend(_additional_data_section(styles, payload, consumed_keys))

    doc.build(
        story,
        onFirstPage=lambda c, d: _draw_header_footer(c, d, report),
        onLaterPages=lambda c, d: _draw_header_footer(c, d, report),
    )

    buffer.seek(0)
    return buffer.getvalue()



# ---------------------------------------------------------------------------
# Chart-ready visualization data
# ---------------------------------------------------------------------------

def _pct(value, scale_from_fraction=True):
    """Coerce a numeric value to a 0-100 percentage, tolerant of bad input."""
    try:
        num = float(value)
    except (TypeError, ValueError):
        return 0.0
    if scale_from_fraction and 0 <= num <= 1:
        num *= 100
    return round(num, 2)


def _build_visualization(report: DiagnosisReport) -> dict:
    payload = report.get_report_json() or {}
    mode = (report.report_type or payload.get('mode') or 'single').strip().lower()
    charts = {}

    if mode == 'batch':
        target_names = payload.get('target_names') or []
        confusion_matrix = payload.get('confusion_matrix')
        if isinstance(confusion_matrix, list) and target_names:
            charts['confusion_matrix'] = {
                'type': 'heatmap',
                'title': 'Confusion Matrix',
                'labels': target_names,
                'matrix': confusion_matrix,
            }

        class_report = payload.get('class_report')
        if isinstance(class_report, list) and class_report:
            charts['class_metrics'] = {
                'type': 'bar',
                'title': 'Precision / Recall / F1 by Class',
                'labels': [row.get('class') for row in class_report],
                'series': [
                    {'name': 'Precision', 'data': [_pct(row.get('precision')) for row in class_report]},
                    {'name': 'Recall', 'data': [_pct(row.get('recall')) for row in class_report]},
                    {'name': 'F1', 'data': [_pct(row.get('f1')) for row in class_report]},
                ],
            }

        macro_avg = payload.get('macro_avg') or {}
        weighted_avg = payload.get('weighted_avg') or {}
        if macro_avg or weighted_avg:
            metrics = ['precision', 'recall', 'f1']
            charts['averages'] = {
                'type': 'bar',
                'title': 'Macro vs Weighted Averages',
                'labels': [_format_label(m) for m in metrics],
                'series': [
                    {'name': 'Macro Avg', 'data': [_pct(macro_avg.get(m)) for m in metrics]},
                    {'name': 'Weighted Avg', 'data': [_pct(weighted_avg.get(m)) for m in metrics]},
                ],
            }

        if payload.get('accuracy') is not None:
            charts['accuracy_gauge'] = {
                'type': 'gauge',
                'title': 'Overall Accuracy',
                'value': _pct(payload.get('accuracy')),
                'max': 100,
            }

        if payload.get('n_test_samples') is not None:
            charts['sample_size'] = {
                'type': 'stat',
                'title': 'Test Samples',
                'value': payload.get('n_test_samples'),
            }

    else:
        band_powers = payload.get('band_powers')
        if isinstance(band_powers, dict) and band_powers:
            charts['band_powers'] = {
                'type': 'bar',
                'title': 'Frequency Band Powers',
                'labels': list(band_powers.keys()),
                'series': [{'name': 'Relative Power (%)', 'data': [_pct(v) for v in band_powers.values()]}],
            }

        ensemble = payload.get('ensemble') or {}
        if ensemble:
            charts['dementia_probability'] = {
                'type': 'gauge',
                'title': 'Dementia Probability',
                'value': _pct(ensemble.get('avg_dementia_prob'), scale_from_fraction=False),
                'max': 100,
                'tier': ensemble.get('confidence_tier'),
            }

        tasks = payload.get('tasks') or {}
        for task_name, task_data in tasks.items():
            if not isinstance(task_data, dict):
                continue
            task_label = task_data.get('task_name') or _format_label(task_name)

            mean_probs = task_data.get('mean_probs')
            if isinstance(mean_probs, dict) and mean_probs:
                charts[f'{task_name}_class_probabilities'] = {
                    'type': 'pie',
                    'title': f'{task_label} — Mean Class Probabilities',
                    'labels': list(mean_probs.keys()),
                    'data': [_pct(v, scale_from_fraction=False) for v in mean_probs.values()],
                }

            epoch_votes = task_data.get('epoch_votes')
            if isinstance(epoch_votes, dict) and epoch_votes:
                charts[f'{task_name}_epoch_votes'] = {
                    'type': 'bar',
                    'title': f'{task_label} — Per-Epoch Votes',
                    'labels': list(epoch_votes.keys()),
                    'series': [{'name': 'Epoch Votes', 'data': list(epoch_votes.values())}],
                }

    return {
        'report_id': report.id,
        'report_type': mode,
        'title': report.title,
        'verdict': report.verdict,
        'confidence': _format_confidence(report.confidence),
        'charts': charts,
    }


@reports_bp.route('/<int:report_id>/visualization', methods=['GET'])
@diagnosis_access_required
def get_report_visualization(report_id: int):
    try:
        user_id = get_current_user_id()
        report = DiagnosisReport.query.filter_by(id=report_id, user_id=user_id).first()
        if not report:
            return jsonify({'success': False, 'message': 'Report not found'}), 404
        return jsonify({'success': True, 'visualization': _build_visualization(report)}), 200
    except Exception as exc:
        return jsonify({'success': False, 'message': 'Failed to build visualization data', 'error': str(exc)}), 500


@reports_bp.route('', methods=['POST'])
@diagnosis_access_required
def save_report():
    try:
        user_id = get_current_user_id()
        data = request.get_json(silent=True) or {}
        payload = _extract_payload(data)

        if not payload:
            return jsonify({'success': False, 'message': 'results payload is required'}), 400

        meta = _build_metadata(payload, data)
        report = DiagnosisReport(
            user_id=user_id,
            title=meta['title'],
            report_type=meta['report_type'],
            source_files=json.dumps(meta['source_files']),
            verdict=meta['verdict'],
            confidence=meta['confidence'],
            summary=meta['summary'],
            report_json=json.dumps(payload),
        )
        db.session.add(report)
        db.session.add(UserActivity(
            user_id=user_id,
            activity_type='diagnosis_report_saved',
            description=f"Saved diagnosis report: {report.title}"
        ))
        db.session.commit()

        return jsonify({'success': True, 'message': 'Report saved successfully', 'report': report.to_dict()}), 201
    except Exception as exc:
        db.session.rollback()
        return jsonify({'success': False, 'message': 'Failed to save report', 'error': str(exc)}), 500


@reports_bp.route('', methods=['GET'])
@diagnosis_access_required
def list_reports():
    try:
        user_id = get_current_user_id()
        limit = request.args.get('limit', 50, type=int)
        fetch_all = request.args.get('all', 'false').lower() == 'true'

        query = DiagnosisReport.query.filter_by(user_id=user_id).order_by(DiagnosisReport.created_at.desc())
        if not fetch_all:
            safe_limit = 20 if not limit or limit < 1 else min(limit, 200)
            query = query.limit(safe_limit)

        reports = query.all()
        return jsonify({'success': True, 'reports': [report.to_dict() for report in reports]}), 200
    except Exception as exc:
        return jsonify({'success': False, 'message': 'Failed to get reports', 'error': str(exc)}), 500


@reports_bp.route('/<int:report_id>', methods=['GET'])
@diagnosis_access_required
def get_report(report_id: int):
    try:
        user_id = get_current_user_id()
        report = DiagnosisReport.query.filter_by(id=report_id, user_id=user_id).first()
        if not report:
            return jsonify({'success': False, 'message': 'Report not found'}), 404
        return jsonify({'success': True, 'report': report.to_dict()}), 200
    except Exception as exc:
        return jsonify({'success': False, 'message': 'Failed to get report', 'error': str(exc)}), 500


@reports_bp.route('/<int:report_id>/download', methods=['GET'])
@diagnosis_access_required
def download_report(report_id: int):
    try:
        user_id = get_current_user_id()
        report = DiagnosisReport.query.filter_by(id=report_id, user_id=user_id).first()
        if not report:
            return jsonify({'success': False, 'message': 'Report not found'}), 404

        file_bytes = _render_report_pdf(report)
        filename = _safe_filename(f"{report.title}-{report.id}.pdf")
        return send_file(
            io.BytesIO(file_bytes),
            mimetype=PDF_MIMETYPE,
            as_attachment=True,
            download_name=filename,
        )
    except Exception as exc:
        return jsonify({'success': False, 'message': 'Failed to download report', 'error': str(exc)}), 500


@reports_bp.route('/download', methods=['GET'])
@diagnosis_access_required
def download_reports():
    try:
        user_id = get_current_user_id()
        ids_param = request.args.get('ids', '')
        report_ids = [int(item) for item in ids_param.split(',') if item.strip().isdigit()]

        if not report_ids:
            return jsonify({'success': False, 'message': 'ids query parameter is required'}), 400

        reports = DiagnosisReport.query.filter(
            DiagnosisReport.user_id == user_id,
            DiagnosisReport.id.in_(report_ids),
        ).order_by(DiagnosisReport.created_at.desc()).all()

        if not reports:
            return jsonify({'success': False, 'message': 'No matching reports found'}), 404

        buffer = io.BytesIO()
        with zipfile.ZipFile(buffer, 'w', zipfile.ZIP_DEFLATED) as archive:
            for report in reports:
                filename = _safe_filename(f"{report.title}-{report.id}.pdf")
                archive.writestr(filename, _render_report_pdf(report))

        buffer.seek(0)
        return send_file(
            buffer,
            mimetype='application/zip',
            as_attachment=True,
            download_name='diagnosis-reports.zip',
        )
    except Exception as exc:
        return jsonify({'success': False, 'message': 'Failed to download reports', 'error': str(exc)}), 500